# Generated by Django 3.2.5 on 2021-07-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
