# Generated by Django 3.2.5 on 2021-07-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210723_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
