# Generated by Django 3.2.5 on 2021-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='describe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='event',
            field=models.CharField(default='', max_length=255),
        ),
    ]
