# Generated by Django 3.2.5 on 2021-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210724_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='describe',
            field=models.TextField(default='', max_length=255),
        ),
    ]
