# Generated by Django 3.2.5 on 2021-07-24 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210724_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productUpload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
