# Generated by Django 3.2.5 on 2021-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210822_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isshipped',
            field=models.BooleanField(default=False),
        ),
    ]
